version: '3.9'

services:
  nexus:
    hostname: nexus
    container_name: nexus
    image: sonatype/nexus3:3.38.1
    restart: always
    privileged: true
    user: root
    ports:
      - '8081:8081'
      - '5000:5000'
    volumes:
       - ./nexus-data:/nexus-data/
    networks:
        - nexus-net

  prometheus:
    image: prom/prometheus:v2.35.0
    container_name: prometheus
    ports:
      - 9000:9090
    volumes:
      - ./prometheus:/etc/prometheus
      - ./prometheus-data:/prometheus
    command: --web.enable-lifecycle  --config.file=/etc/prometheus/prometheus.yml
    restart: always
    networks:
        - nexus-net
  
  grafana:
    image: grafana/grafana:8.5.2
    container_name: grafana
    ports:
      - 3000:3000
    restart: unless-stopped
    volumes:
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./grafana-data:/var/lib/grafana
      - ./grafana/conf/grafana.ini:/etc/grafana/grafana.ini
    networks:
      - nexus-net

  nginx:
    image: nginx:1.21
    container_name: nginx
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - nexus-net

  nginx-exporter:
    image: nginx/nginx-prometheus-exporter:0.9.0
    container_name: nginx-exporter
    restart: always
    depends_on:
      - nginx
    environment:
        - SCRAPE_URI=http://nginx/nginx_status
        - TELEMETRY_PATH=/metrics
        - NGINX_RETRIES=10
    ports:
      - 9113:9113
    networks:
      - nexus-net

networks:
    nexus-net:
        name: nexus-net